export const cardTemplateStyle = (x, y, cardSize) => ({
  position: 'absolute',
  left: x + (cardSize / 2) - (140 / 2),
  top: y - 70,
  width: '140px',
  textAlign: 'center',
  fontSize: '1rem',
  background: '#000000ff',
  border: '1px solid #ccc',
  borderRadius: '8px',
  marginBottom: '8px',
  padding: '4px 8px',
  zIndex: 2,
  resize: 'none',
  overflow: 'auto',
  whiteSpace: 'pre-wrap',
});
